import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import WholeSideNav from "@/app/_comps/WholeSideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // get the current route
  // const route = 
  // const isLogin = false;
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
          {isLogin && (
            <div className="w-full flex-none md:w-64">
              <WholeSideNav />
            </div>
          )}
          <div className="flex-grow p-6 md:overflow-y-auto md:p-12">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
